<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<title>Chapter 4: Exercises</title>

<script src="libs/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.1/css/united.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.1/shim/respond.min.js"></script>
<style type="text/css">
    body {
        padding-top: 20px;
        padding-bottom: 20px;
    }
    @media (max-width: 979px) {
        body {
            padding-top: 0;
        }
    }

    @media (min-width: 980px) {
        .section h2 {
            padding-top: 52px;
            margin-top: -52px;
        }
        .section h3 {
            padding-top: 52px;
            margin-top: -52px;
        }
    }

    p {
        font-size: 13px;
    }

    #disqus_thread {
        margin-top: 45px;
    }
</style>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #0000ff; }
code > span.ch { color: #008080; }
code > span.st { color: #008080; }
code > span.co { color: #008000; }
code > span.ot { color: #ff4000; }
code > span.al { color: #ff0000; }
code > span.er { font-weight: bold; }
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">

<h2>Doing Bayesian Data Analysis</h2>
<h5>Working through the book <a href="http://www.amazon.co.uk/Doing-Bayesian-Data-Analysis-Tutorial/dp/0123814855/ref=sr_1_2?s=books&ie=UTF8&qid=1432494439&sr=1-2&keywords=doing+bayesian+data+analysis">Doing Bayesian Data Analysis</a> (ed.1) by John Kruschke, inc. examples and exercises.</h5>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#dba-nav">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="http://durtal.github.io" class="navbar-brand">durtal.github.io</a>
        </div>
        <div class="collapse navbar-collapse" id="dba-nav">
            <ul class="nav navbar-nav">
                <li>
                    <a href="index.html">DBDA Home</a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        Exercises <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="chapter2-exercises.html">Chapter 2</a>
                        </li>
                        <li>
                            <a href="chapter3-exercises.html">Chapter 3</a>
                        </li>
                        <li>
                            <a href="chapter4-exercises.html">Chapter 4</a>
                        </li>
                        <li>
                            <a href="chapter5-exercises.html">Chapter 5</a>
                        </li>
                        <li>
                            <a href="chapter6-exercises.html">Chapter 6</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        Other <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="how-not-to-be-wrong-roulette.html">How Not To Be Wrong</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div id="header">
<h1 class="title">Chapter 4: Exercises</h1>
</div>


<div id="bayes-rule" class="section level2">
<h2>Bayes Rule</h2>
<div id="section" class="section level3">
<h3>4.1</h3>
<p>Suppose that in the general population, the probability of having a particular rare disease is 1 in 1000. We denote the true presence or absence of the disease as the value of a parameter, <span class="math">\(\theta\)</span>, that can have the value <strong><span class="math">\(\theta\)</span> = 1</strong> if disease is present, or the value <strong><span class="math">\(\theta\)</span> = 0</strong> if the disease is absent. The base rate of the disease is therefore denoted as <span class="math">\(p(\theta = 1) = 0.001\)</span>. This is our prior belief that a person, selected at random, has the disease.</p>
<p>Suppose there is a test for the disease that has 99% hit rate, that means if a person has the disease, then the test result if positive 99% of the time. We denote a positive test as <strong>D = +</strong> and a negative test as <strong>D = -</strong>. The observed test result is a bit of data that we will use to modify our belief about the value of the underlying disease parameter. The hit rate is expressed as <span class="math">\(p(D = + | \theta = 1) = 0.99\)</span>. The test also has a false alarm rate of 5%, this means that 5% of the time when the disease is not present, the test falsely indicates that the disease is present. We denote the false alarm rate as <span class="math">\(p(D = + | \theta = 0) = 0.05\)</span>.</p>
<p>Suppose we sample a person at random from the population, administer the test, and it comes up positive.</p>
<blockquote>
<p>What is the posterior probability that the person has the disease?</p>
</blockquote>
<p><span class="math">\[\begin{align}
p(\theta = 1 | D = +) 
&amp; = \frac{p(D = + | \theta = 1)p(\theta = 1)}{p(D = +)} \\
&amp; = \frac{p(D = + | \theta = 1)p(\theta = 1)}{\left[p(D = + | \theta = 1)p(\theta = 1) + p(D = + | \theta = 0)p(\theta = 0)\right]} \\
&amp; = \frac{0.99 * 0.001}{(0.99 * 0.001) + (0.05 * 0.999)} \\
&amp; = 0.0194
\end{align}\]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">(posterior4<span class="fl">.1</span> &lt;-<span class="st"> </span>(<span class="fl">0.99</span> *<span class="st"> </span><span class="fl">0.001</span>) /<span class="st"> </span>((<span class="fl">0.99</span> *<span class="st"> </span><span class="fl">0.001</span>) +<span class="st"> </span>(<span class="fl">0.05</span> *<span class="st"> </span>(<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.001</span>))))</code></pre>
<pre><code>## [1] 0.01943463</code></pre>
</div>
<div id="section-1" class="section level3">
<h3>4.2</h3>
<p>Continuing from the previous exercise, suppose that the same randomly selected person is retested after the first test comes back positive, and on the retest the result is negative. Now</p>
<blockquote>
<p>what is the probability that the person has the disease</p>
</blockquote>
<pre class="sourceCode r"><code class="sourceCode r">(newposterior4<span class="fl">.2</span> &lt;-<span class="st"> </span>((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.99</span>) *<span class="st"> </span>posterior4<span class="fl">.1</span>) /<span class="st"> </span>(((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.99</span>) *<span class="st"> </span>posterior4<span class="fl">.1</span>) +<span class="st"> </span>((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.05</span>) *<span class="st"> </span>(<span class="dv">1</span> -<span class="st"> </span>posterior4<span class="fl">.1</span>))))</code></pre>
<pre><code>## [1] 0.0002085862</code></pre>
</div>
<div id="section-2" class="section level3">
<h3>4.4</h3>
<p>Consider again the disease and diagnostic test of the previous two exercises. Suppose that a person selected at random from the population gets the test and it comes back negative.</p>
<blockquote>
<p>Compute the probability that the person has the disease</p>
</blockquote>
<pre class="sourceCode r"><code class="sourceCode r">(posterior4<span class="fl">.4</span> &lt;-<span class="st"> </span>((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.99</span>) *<span class="st"> </span><span class="fl">0.001</span>) /<span class="st"> </span>(((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.99</span>) *<span class="st"> </span><span class="fl">0.001</span>) +<span class="st"> </span>((<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.05</span>) *<span class="st"> </span>(<span class="dv">1</span> -<span class="st"> </span><span class="fl">0.001</span>))))</code></pre>
<pre><code>## [1] 0.00001053674</code></pre>
<p>The person is then retested, and on the second test the result is positive…</p>
<blockquote>
<p>Compute the probability that the person has the disease. How does this compare with the result from 4.2</p>
</blockquote>
<pre class="sourceCode r"><code class="sourceCode r">(newposterior4<span class="fl">.4</span> &lt;-<span class="st"> </span>((<span class="fl">0.99</span> *<span class="st"> </span>posterior4<span class="fl">.4</span>) /<span class="st"> </span>((<span class="fl">0.99</span> *<span class="st"> </span>posterior4<span class="fl">.4</span>) +<span class="st"> </span>(<span class="fl">0.05</span> *<span class="st"> </span>(<span class="dv">1</span> -<span class="st"> </span>posterior4<span class="fl">.4</span>)))))</code></pre>
<pre><code>## [1] 0.0002085862</code></pre>
<p>The result matches, <strong>0.0002086 = 0.0002086</strong></p>
</div>
<div id="section-3" class="section level3">
<h3>4.5</h3>
<p>Cognitive neuroscientists investigate which areas of the brain are active during particular mental tasks. In many situations, researchers observe that a certain region of the brain is active and infer that a particular cognitive function is therefore being carried out. Poldrack (2006) cautioned that such inferences are not necessarily firm and need to be made with Bayes’ rule in mind. Poldrack (2006) reported the following frequency table of previous studies that involved any language related task (specifically phonological and semantic processing) and whether or not a particular region of interest (ROI) in the brain was activated:</p>
<table>
<thead>
<tr class="header">
<th align="left">Active/Study</th>
<th align="left">Language Study</th>
<th align="left">Not Language Study</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Activated</td>
<td align="left">166</td>
<td align="left">199</td>
</tr>
<tr class="even">
<td align="left">Not Activated</td>
<td align="left">703</td>
<td align="left">2154</td>
</tr>
</tbody>
</table>
<blockquote>
<p>Suppose that a new study is conducted and finds that the ROI is activated. If the prior probability that the task involves language processing is 0.5, what is the posterior probability, given the ROI is activated?</p>
</blockquote>
<p><span class="math">\[\begin{align}
p(Lang. | ROI active)
&amp; = \frac{p(ROI active | Lang)p(Lang)}{(p(ROI active | Lang)p(Lang)) + (p(ROI active | Not Lang)p(Not Lang))} \\
&amp; = \frac{\frac{166}{166 + 703}*0.5}{\left(\frac{166}{(166 + 703)}*0.5\right) + \left(\frac{199}{199 + 2154}*0.5\right)} \\
&amp; = 0.693
\end{align}\]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">(posterior4<span class="fl">.5</span> &lt;-<span class="st"> </span>((<span class="dv">166</span> /<span class="st"> </span>(<span class="dv">166</span> +<span class="st"> </span><span class="dv">703</span>)) *<span class="st"> </span><span class="fl">0.5</span>) /<span class="st"> </span>(((<span class="dv">166</span> /<span class="st"> </span>(<span class="dv">166</span> +<span class="st"> </span><span class="dv">703</span>)) *<span class="st"> </span><span class="fl">0.5</span>) +<span class="st"> </span>((<span class="dv">199</span> /<span class="st"> </span>(<span class="dv">199</span> +<span class="st"> </span><span class="dv">2154</span>)) *<span class="st"> </span><span class="fl">0.5</span>)))</code></pre>
<pre><code>## [1] 0.6931285</code></pre>
</div>
<div id="section-4" class="section level3">
<h3>4.6</h3>
<p>Derive the posterior probability in Figure 4.1 (shown below) by hand. The prior has <span class="math">\(p(\theta = 0.25) = 0.25\)</span>, <span class="math">\(p(\theta = 0.5) = 0.5\)</span> and <span class="math">\(p(\theta = 0.75) = 0.25\)</span>. The data consist of a specific sequence of flips with three heads and nine tails.</p>
<div class="row">
<div class="col-sm-4">
<p><img src="chapter4-exercises_files/figure-html/unnamed-chunk-8-1.png" title="" alt="" width="672" /></p>
</div>
<div class="col-sm-4">
<p><img src="chapter4-exercises_files/figure-html/unnamed-chunk-9-1.png" title="" alt="" width="672" /></p>
</div>
<div class="col-sm-4">
<p><img src="chapter4-exercises_files/figure-html/unnamed-chunk-10-1.png" title="" alt="" width="672" /></p>
</div>
</div>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co"># theta and pTheta</span>
theta &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>)
pTheta &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.25</span>)

<span class="co"># coin flip sequence</span>
flips &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">3</span>),<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">9</span>))
nHeads &lt;-<span class="st"> </span><span class="kw">sum</span>(flips)
nTails &lt;-<span class="st"> </span><span class="kw">length</span>(flips) -<span class="st"> </span>nHeads 

<span class="co"># data given theta (the likelihood)</span>
pDGivenTheta &lt;-<span class="st"> </span>theta^nHeads *<span class="st"> </span>(<span class="dv">1</span>-theta)^nTails

<span class="co"># the posterior</span>
pData =<span class="st"> </span><span class="kw">sum</span>( pDGivenTheta *<span class="st"> </span>pTheta )
(<span class="dt">pThetaGivenData =</span> pDGivenTheta *<span class="st"> </span>pTheta /<span class="st"> </span>pData)</code></pre>
<pre><code>## [1] 0.7054333023 0.2935990252 0.0009676726</code></pre>
<p>Do the posterior probabilities, 0.7054333, 0.293599, 0.0009677, sum to 1.0, <strong>TRUE</strong></p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
